#9 buscando perguntas e removendo uma pergunta pelo id
Schwaaan/projetoPi2Fase pull request #10
Opened 2020-11-05 00:05 UTC by Schwaaan

2020-11-06 00:06 UTC, AndrewsVieira commented
levando em consideração o que o professor Camilo disse, não seria melhor a gente usar o objeto ao invés do id?

2020-11-09 22:55 UTC, AndrewsVieira requested changes
levando em consideração o que o professor Camilo disse, não seria melhor a gente usar o objeto ao invés do id?

2020-11-09 23:27 UTC, AndrewsVieira requested changes

2020-11-09 23:27 UTC, AndrewsVieira commented on src/BE/services/QuestionService.java
> +  public void deleteQuestionById(Integer id){
Usar o objeto Question ao invés de id quando quiser deletar

2020-11-10 12:04 UTC, victorgeorges approved these changes

2020-11-11 01:39 UTC, AndrewsVieira approved these changes

2020-11-11 01:46 UTC, Schwaaan commented on src/BE/services/QuestionService.java
> +  public void deleteQuestionById(Integer id){
blz

2020-11-11 02:13 UTC, merged